../rtl/rv32_pkg.sv
../rtl/adder_9bit.sv
../rtl/adder.sv
../rtl/alu.sv
../rtl/alup.sv
../rtl/branch_comparator.sv
../rtl/control_logic.sv
../rtl/data_memory.sv
../rtl/decoder.sv
../rtl/forwarding_unit.sv
../rtl/hazard_detection.sv
../rtl/imem.sv
../rtl/immgen.sv
../rtl/pc_selection.sv
../rtl/pc.sv
../rtl/pipe_reg.sv
../rtl/regfile.sv
../rtl/rv32im_pipeline.sv
   
../tb/tb_rv32im_pipeline.sv
